name: CI/CD with Docker Compose

on:
  push:
    branches: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Make application.yml
        run: |
          mkdir -p ./artichat/src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./artichat/src/main/resources/application.yml

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          cd ./artichat
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build & push
        uses: docker/build-push-action@v6
        with:
          context: ./artichat
          file: ./artichat/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_REPO }}:latest

      - name: Deploy to Server with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            set -e
            sudo echo "${{ secrets.DOCKER_COMPOSE }}" > ./docker-compose.yml
            sudo docker compose down
            sudo docker pull ${{ secrets.DOCKER_REPO }}:latest
            sudo docker compose up -d --pull always --force-recreate
            sudo docker system prune -af
